### ISSUE TITLE
Upgrade for peer deps vue-template-compiler, vue-template-es2015-compiler

### ISSUE THREAD

**Issue by evictor** [vire/jest-vue-preprocessor#135]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request
```

**Current behavior**

package.json specifies peer deps for `vue-template-compiler@2.5.x` and `vue-template-es2015-compiler@1.6.x`.

**Expected behavior**

There have been releases up to `vue-template-compiler@2.6.10` and `vue-template-es2015-compiler@1.9.1`.

It would be nice if the peer dependencies allowed these minor versions instead of locking to minor versions 2.5.x and 1.6.x respectively.

**What is the motivation / use case for changing the behavior?**

Remove warnings during dep installation.

* **jest-vue-preprocessor:** 1.1.X

1.5.0

**Comment by vire** [comment]
@evictor Thanks for submitting an issue, I will look at it in next days, perhaps can you submit a PR?

**Comment by evictor** [comment]
Thank you for doing that @djusv

**Comment by vire** [comment]
@evictor @djusv I've published latest version you can test and fill issues if something does not work properly
