### ISSUE TITLE
some devDependencies are required

### ISSUE THREAD

**Issue by ejfrancis** [vire/jest-vue-preprocessor#18]
Currently if you install this in a fresh Vue project and run your tests, you'll get an error about the following packages missing:

* `vue-template-compiler`
* `vue-template-es2015-compiler`

This is because they're marked as `devDepedencies`, so they don't get installed. I think these should be marked as `peerDependencies` or just plain `dependencies`.

**Comment by vire** [comment]
@ejfrancis published v1.0.0 with the upper libs set to deps

**Comment by ejfrancis** [comment]
thanks!

**Comment by wopian** [comment]
This should be `peerDependencies`. Adding it as a `dependency` means the module is downloaded twice (if they target different versions) to run the tests.

As a result, my tests are now failing, as its locked to `vue-template-compiler@2.2.6`, whereas i'm using `vue@2.3.3`, so get a `vue package mismatch` error.

https://travis-ci.org/wopian/hibari/builds/240177456

**Comment by vire** [comment]
@wopian I'll try to upgrade deps versions today

**Comment by vire** [comment]
@wopian can you try with v1.0.1 - see #21

**Comment by wopian** [comment]
@vire updated when it was released - works 👌👌
