### ISSUE TITLE
Vue Template Complier Version

### ISSUE THREAD

**Issue by Austio** [vire/jest-vue-preprocessor#21]
Hello thanks for this preprocessor!

**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request
```

**Current behavior**
Vue Template Compiler is locked at 2.2.6.  This is preventing running tests on my version of vue which is 2.3.3

Can i set that to at least 2.2.6 instead of exactly 2.2.6 and send you a PR for the new version requirement?

In package.json
```
    "vue-template-compiler": "2.2.6",
```

**Expected behavior**

**Comment by vire** [comment]
Can you try now with `v1.0.1` ?

**Comment by mathieumure** [comment]
Thanks for the quick fix, it works for me
