### ISSUE TITLE
vue-template-compiler should be a peer dependency

### ISSUE THREAD

**Issue by eddyerburgh** [vire/jest-vue-preprocessor#29]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request
```

**Current behavior**
vue-template-compiler is a dependency

**Expected behavior**
It should be a peer dependency, so that users can choose which version of Vue they compile. If it's a dependency then they must use the Vue version that matches the vue-template-compiler version used by jest-vue-processor

**What is the motivation / use case for changing the behavior?**

I can't use this with vue 2.4.2. It would be better if I could update vue-template-compiler to whatever version I wanted.

**Comment by gaoupon** [comment]
I encountered the same problem. I can't use jest-vue-preprocessor 1.0.1 with Vue 2.4.1.
