### ISSUE TITLE
Babel config is hard-coded

### ISSUE THREAD

**Issue by joezimjs** [vire/jest-vue-preprocessor#4]
Should search for a `.babelrc` file and/or the `babel` property in the `package.json` file instead of using hard-coded babel configuration.

**Comment by vire** [comment]
Can you make a PR for that?

**Comment by jerexyz** [comment]
you can use `babel env options` solve that
https://babeljs.io/docs/usage/babelrc/#env-option

**Comment by joezimjs** [comment]
@jerexyz Yup, then we'd need to specify in the docs what environment we're targeting. Also, that doesn't solve how to grab those options because they could be in a .babelrc file, in the package.json file, or they may want a different file name, so we'd need to be able to allow them to specify which file it's in, or we could accept a config being passed in directly, potentially. 

I'm not sure when I'll have time to work on the PR, but if you haven't gotten around to it before I do, I'll try to do it.

**Comment by jerexyz** [comment]
https://github.com/vire/jest-vue-preprocessor/pull/9

**Comment by jerexyz** [comment]
[find-babel-config](https://www.npmjs.com/package/find-babel-config) will find  babel  config from .babelrc or package.json  
I don't think we should support a custom file name,that is  too horrible.
