### ISSUE TITLE
TypeError: Jest: a transform's `process` function must return a string,

### ISSUE THREAD

**Issue by RokkerRuslan** [vire/jest-vue-preprocessor#42]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**

Fails with that errors:
```
$ npm test

> webpack-test2@1.0.0 test /home/r/w/webpack-test2
> jest

Failed to compile src with `tsc` at `vue-preprocessor`
 FAIL  tests/add.test.ts
  ● Test suite failed to run

    TypeError: Jest: a transform's `process` function must return a string, or an object with `code` key containing this string.
      
      at ScriptTransformer.transformSource (node_modules/jest-runtime/build/script_transformer.js:227:15)
      at Object.<anonymous> (tests/add.test.ts:6:15)

  console.info node_modules/vue/dist/vue.common.js:8248
    You are running Vue in development mode.
    Make sure to turn on production mode when deploying for production.
    See more tips at https://vuejs.org/guide/deployment.html

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.509s
Ran all test suites.
npm ERR! Test failed.  See above for more details.

```

**Expected behavior**

Mormal completion of tests

**Minimal reproduction of the problem with instructions**
Minimal example here may be big) so I created minimal test example project.
Project contains vue app, and 2 type of tests. Testing .ts files and .vue componet.

https://gitlab.com/rokkerruslan/jest-ts-vue-test

**What is the motivation / use case for changing the behavior?**

I need testing as simple ts files and vue components files.

**Please tell us about your environment:**

npm 5.5.1

* **jest-vue-preprocessor:** 1.1.X

1.3.1

* **Node version :** [ OSX | Linux | Windows ]
v9.0.0

* **Platform:** [ OSX | Linux | Windows ]
Linux rpc 4.10.0-37-generic #41~16.04.1-Ubuntu SMP Fri Oct 6 22:42:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Thanks for any asnwers!

**Comment by khanharis87** [comment]
@RokkerRuslan did you solve this issue?

**Comment by Michael-Gungaram** [comment]
Any solution about this? Have the same issue.

**Comment by RehanSaeed** [comment]
Same here, any solutions?

**Comment by jeroenschieven** [comment]
@khanharis87 @Michael-Gungaram @RehanSaeed Not sure if still relevant for you guys, but maybe it is for everyone else having this issue.

I had the same problem. Turned out that the problem only occurred when using Object spread syntax.  The object spread syntax isn't supported by babel-core, so you need to install a plugin for that and add it to your .babelrc file. Check https://babeljs.io/docs/plugins/transform-object-rest-spread for more information about the plugin.

The problem could also occur with any other es7/es[future-releases] syntax your using in your files which is not supported by babel-core.

**Comment by samuelterra22** [comment]
thx @jeroenschieven ! I was having the same problem.

**Comment by Prior99** [comment]
I am experiencing the same problem while using Typescript. Any solutions?

**Comment by MiguelSi6** [comment]
i had to add "jest-junit": "13.0.0", to package.json and the problem went away
