### ISSUE TITLE
babel-plugin-transform-runtime should be a dependency (not dev-dependency)

### ISSUE THREAD

**Issue by borisdiakur** [vire/jest-vue-preprocessor#6]
I was getting a _Failed to compile scr with `babel` at `vue-preprocessor`_ until I found out that the babel-plugin-transform-runtime package was missing, by adding the error to the console.log, and then just installed it as a dev dependency. I think it should be a dependency of jest-vue-preprocessor.

**Comment by vire** [comment]
Can you add a PR? should be fair easy :)

**Comment by borisdiakur** [comment]
[PR](https://github.com/vire/jest-vue-preprocessor/pull/7) added.

**Comment by vire** [comment]
I'll publish the new version to npm today evening
